version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: 2shortplanks/perl-advent-builder:latest
    steps:
      - checkout

      # build the current advent calendar
      - run:
        command: |
          cd /root/project/2021
          advcal -c advent.ini

      # and save it as an artifact
      - store_artifacts:
          path: /root/project/2021/out

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
